### ISSUE TITLE
JOLNET information in the configuration file

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-sdn-do#10]
I propose a [jolnet] section, which contains the following fields:
* jolnet = false (true)
* available_ids = 280-289,62,737,90-95,290-299,13-56,92,57-82 

This last field is currently in the [vlan] section, which would disappear.

I think that this organization, which puts togeter all the information related to the jolnet, is more clear.

**Comment by gabrielecastellano** [comment]
Why available vlan should be an info related with the jolnet?

**Comment by ivanocerrato** [comment]
Currently, we only use this information in theJOLNET.
In other set up we let, to the SDN-DO, the freedom to use any vlan ID it wants to.
Even, I think that, if the SDN-DO is not in JOLNET mode, it does not consider the available_ids. Isn't it?

**Comment by gabrielecastellano** [comment]
It consider avaible vlan as well it is not in jolnet mode

**Comment by ivanocerrato** [comment]
Ok, I was not aware of this. 
Just for my curiosity, what happens if we don't specify any VLAN?

**Comment by gabrielecastellano** [comment]
It returns an error during the deployment of a flow if there are no more available vlans.

**Comment by ivanocerrato** [comment]
Ok, thanks
