### ISSUE TITLE
Change in API

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-sdn-do#17]
The northbound API should be changed so that it is the same of the northbound API of the FROG orchestrator.

@gabrielecastellano Farman will take care of this, although it is possible that he well have some questions for you.

**Comment by farmanullahcs** [comment]
Fixed in the branch, [frog4-deployment](https://github.com/netgroup-polito/frog4-sdn-do/tree/frog4-deployment)
