### ISSUE TITLE
Documentation about priorities to be used

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-sdn-do#5]
The documentation should say that, in the NFFG, priorities higher than 40000 must be used.

**Comment by ivanocerrato** [comment]
@gabrielecastellano does this issue make sense? 

And where can be set priorities for applications?

**Comment by gabrielecastellano** [comment]
Priority of nffg flows are not propagated on onos application for now (but it can be implemented easily).
However, our applications use a priority greater than 40000 by default

**Comment by frisso** [comment]
@gabrielecastellano can you please improve the documentation and close this issue?

**Comment by gabrielecastellano** [comment]
Closed with 9529c179bfb5a581e27dde1f46c48b6e2be606c0.
As the feature has been implemented, there are no reasons to specify something in readme. NFFG priorities are now used also by applications.
