### ISSUE TITLE
nffg deploy error

### ISSUE THREAD

**Issue by rbrtbnfgl** [netgroup-polito/frog4-sdn-do#6]
On master
https://github.com/netgroup-polito/frog4-sdn-do/blob/master/do_core/do.py#L514
It does not require any input but it given on 
https://github.com/netgroup-polito/frog4-sdn-do/blob/master/do_core/do.py#L75
https://github.com/netgroup-polito/frog4-sdn-do/blob/master/do_core/do.py#L140

**Comment by gabrielecastellano** [comment]
Fixed in bcebca3dc7ecbeecb2c2b4d04f278c53698e8b1d
