### ISSUE TITLE
How to create a new user

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-sdn-do#7]
Please, write a script to create a new user, then add the proper documentation here https://github.com/netgroup-polito/frog4-sdn-do/blob/master/README_INSTALL.md#how-to-create-new-user

**Comment by frisso** [comment]
Could you please check that instructions are ok?
The script is named scripts/add_user.py, but instructions say "scripts.add_user".
IN addition, move this into teh proper section of the README (currently, the "add user" section has still a TODO)

**Comment by ivanocerrato** [comment]
The command is correct. 
The README has been fixed.
